### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by pombredanne** [ssato/rpmkit#6]
Hi!
thank you for this tool.

The readme states:
> This is a collection of some rpm related tools distributed under GPL3+/GPLv2+/MIT.

I wonder about the license for this tool. Is this a choice of GPL 2, 3 or MIT or a combo where all apply?

**Comment by ssato** [comment]
It's a collection of my scripts and each one is distributed under different license.
For example, 

- MIT: https://github.com/ssato/rpmkit/blob/master/rpmkit/buildsrpm.py
- GPLv2: https://github.com/ssato/rpmkit/blob/master/rpmkit/swapi.py
- GPLv3: https://github.com/ssato/rpmkit/blob/master/rpmkit/yum_makelistcache.p

**Comment by pombredanne** [comment]
@ssato thank you for the clarification!
